name: Test, Build, Package and Optionally Release

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
     - id: build
       run: |
         make
       
